package ru.comfortsoft.bas.tests.api.objects;

import io.qameta.allure.Owner;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import io.restassured.response.Response;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Tags;
import org.junit.jupiter.api.Test;
import ru.comfortsoft.bas.models.objects.CreateObjectErrorResponseModel;
import ru.comfortsoft.bas.models.objects.CreateObjectRequestModel;
import ru.comfortsoft.bas.models.objects.CreateObjectResponseModel;
import ru.comfortsoft.bas.tests.api.BaseApi;
import ru.comfortsoft.bas.utilities.RandomData;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertAll;

@DisplayName("Create object API tests")
public class CreateObjectDictTests extends BaseApi {
    private final RandomData randomValues = new RandomData();

    @Test
    @DisplayName("Create a new object with auto-generated code")
    @Tags({@Tag("smoke"), @Tag("regress")})
    @Severity(SeverityLevel.CRITICAL)
    @Owner("Yulia Azovtseva")
    void createObjectWithAutoGeneratedCodeTest() {
        String objType = randomValues.getRandomObjectType().getObjectTypeCode(),
                address = randomValues.generateRandomAddress(),
                parentCode = randomValues.getRandomDistrict().getCode();

        CreateObjectRequestModel randomDataObject = CreateObjectRequestModel.builder()
                .objType(objType)
                .address(address)
                .name("Object Name")
                .parentCode(parentCode)
                .build();
        Response response = objectsApi.createObject(randomDataObject);
        CreateObjectResponseModel responseObject = response.as(CreateObjectResponseModel.class);

        assertAll(
                () -> assertThat(response.getStatusCode()).isEqualTo(200),
                () -> assertThat(responseObject.getAddress()).isEqualTo(address),
                () -> assertThat(responseObject.getParentCode()).isEqualTo(parentCode)
        );
        objectsApi.deleteObject(responseObject.getCode());
    }

    @Test
    @DisplayName("Create a new object with user-defined code")
    @Tags({@Tag("smoke"), @Tag("regress")})
    @Severity(SeverityLevel.NORMAL)
    @Owner("Yulia Azovtseva")
    void createObjectWithUserDefinedCodeTest() {
        String objType = randomValues.getRandomObjectType().getObjectTypeCode(),
                address = randomValues.generateRandomAddress(),
                parentCode = randomValues.getRandomDistrict().getCode(),
                code = randomValues.generateRandomObjectCode();

        CreateObjectRequestModel randomDataObject = CreateObjectRequestModel.builder()
                .code(code)
                .objType(objType)
                .address(address)
                .name("Object Name")
                .parentCode(parentCode)
                .build();
        Response response = objectsApi.createObject(randomDataObject);
        CreateObjectResponseModel responseObject = response.as(CreateObjectResponseModel.class);

        assertAll(
                () -> assertThat(response.getStatusCode()).isEqualTo(200),
                () -> assertThat(responseObject.getAddress()).isEqualTo(address),
                () -> assertThat(responseObject.getParentCode()).isEqualTo(parentCode),
                () -> assertThat(responseObject.getCode()).isEqualTo(code)
        );
        objectsApi.deleteObject(code);
    }

    @Test
    @DisplayName("Attempt to create an object with missing 'name' parameter")
    @Tags({@Tag("smoke"), @Tag("regress")})
    @Severity(SeverityLevel.NORMAL)
    @Owner("Yulia Azovtseva")
    void createObjectWithMissedNameParamTest() {
        CreateObjectRequestModel randomDataObject = CreateObjectRequestModel.builder()
                .objType(randomValues.getRandomObjectType().getObjectTypeCode())
                .address(randomValues.generateRandomAddress())
                .parentCode(randomValues.getRandomDistrict().getCode())
                .build();
        Response response = objectsApi.createObject(randomDataObject);
        CreateObjectErrorResponseModel responseObject = response.as(CreateObjectErrorResponseModel.class);

        assertAll(
                () -> assertThat(response.getStatusCode()).isEqualTo(400),
                () -> assertThat(responseObject.getErrorCode()).isEqualTo("IllegalParameterError"),
                () -> assertThat(responseObject.getErrorData().getParam()).isEqualTo("name")
        );
    }

    @Test
    @DisplayName("Attempt to create an object with missing 'parentCode' parameter")
    @Tags({@Tag("smoke"), @Tag("regress")})
    @Severity(SeverityLevel.NORMAL)
    @Owner("Yulia Azovtseva")
    void createObjectWithMissingParentParamTest() {
        CreateObjectRequestModel randomDataObject = CreateObjectRequestModel.builder()
                .objType(randomValues.getRandomObjectType().getObjectTypeCode())
                .address(randomValues.generateRandomAddress())
                .name("Object Name")
                .build();
        Response response = objectsApi.createObject(randomDataObject);
        CreateObjectErrorResponseModel responseObject = response.as(CreateObjectErrorResponseModel.class);

        assertAll(
                () -> assertThat(response.getStatusCode()).isEqualTo(400),
                () -> assertThat(responseObject.getErrorCode()).isEqualTo("IllegalParameterError"),
                () -> assertThat(responseObject.getErrorData().getParam()).isEqualTo("parentCode")
        );
    }
}
